# Skimming from SILSO Sunspot Number data

Plase download Sunspot Number data from:

https://www.sidc.be/silso/datafiles

in CSV format. Take into account data is available from year 1818. In your PC it will download as:

    SN_d_tot_V2.0.csv

It has the following columns:

    ------------------------------------------------------------------------------
    CSV
    -------------------------------------------------------------------------------
    Filename: SN_d_tot_V2.0.csv
    Format: Comma Separated values (adapted for import in spreadsheets)
    The separator is the semicolon ';'.

    Contents:
    Column 1-3: Gregorian calendar date
    - Year
    - Month
    - Day
    Column 4: Date in fraction of year.
    Column 5: Daily total sunspot number. A value of -1 indicates that no number is available for that day (missing value).
    Column 6: Daily standard deviation of the input sunspot numbers from individual stations.
    Column 7: Number of observations used to compute the daily value.
    Column 8: Definitive/provisional indicator. '1' indicates that the value is definitive. '0' indicates that the value is still provisional.
    
Please, move file to `snData` directory.

This jupyter will work in software dir:

    ~/min03nasa_2023/to3soft_13ABR2018_org/

## Chosing years for analysis

In [1]:
iniYY = 1979
endYY = 2022

In [2]:
df<- read.csv2("~/min03nasa_2023/to3soft_13ABR2018_org/snData/SN_d_tot_V2.0.csv", sep = ';',header = F)

In [3]:
head(df)

  V1   V2 V3 V4       V5 V6    V7 V8
1 1818 1  1  1818.001 -1  -1.0 0  1
2 1818 1  2  1818.004 -1  -1.0 0  1
3 1818 1  3  1818.007 -1  -1.0 0  1
4 1818 1  4  1818.010 -1  -1.0 0  1
5 1818 1  5  1818.012 -1  -1.0 0  1
6 1818 1  6  1818.015 -1  -1.0 0  1

In [4]:
df <- type.convert(df, as.is = TRUE)

In [5]:
head(df)

  V1   V2 V3 V4       V5 V6 V7 V8
1 1818 1  1  1818.001 -1 -1 0  1
2 1818 1  2  1818.004 -1 -1 0  1
3 1818 1  3  1818.007 -1 -1 0  1
4 1818 1  4  1818.010 -1 -1 0  1
5 1818 1  5  1818.012 -1 -1 0  1
6 1818 1  6  1818.015 -1 -1 0  1

In [6]:
#df[df$V8 == 0,]

In [7]:
#df_skim<-df[(df$V8 != 0)&(df$V1>=iniYY)&(df$V1<=endYY),]
df_skim<-df[(df$V1>=iniYY)&(df$V1<=endYY), ]

In [8]:
head(df_skim)

      V1   V2 V3 V4       V5  V6   V7 V8
58805 1979 1  1  1979.001 224 10.0 1  1
58806 1979 1  2  1979.004 224 10.0 1  1
58807 1979 1  3  1979.007 270 11.0 1  1
58808 1979 1  4  1979.010 222 10.0 1  1
58809 1979 1  5  1979.012 207  9.6 1  1
58810 1979 1  6  1979.015 245 10.5 1  1

In [9]:
write.table(df_skim, sep = '\t', file = "sndataskim.dat", col.names=FALSE, row.names=FALSE)
write.table(df, sep = '\t', file = "sndata.dat", col.names=FALSE, row.names=FALSE)

In [10]:
system("mv sndataskim.dat snData/")
system("mv sndata.dat snData/")

Anexo. Check for missing values into Sunspot Number data.

df_aux<-df_s[1,]
df_aux<-df_aux[-1,]
cdmax=c(31,28,31,30,31,30,31,31,30,31,30,31)
cdmaxb=c(31,29,31,30,31,30,31,31,30,31,30,31)
ndays = 0
for(i in 1:nrow(df_s)){
    YY = df_s[i,c('V1')]
    MM ´= df_s[i,c('V2')]
    DD = df_s[i,c('V3')]
    
    if(YY%%4 != 0){
        dmax = cdmax            
    } else {
        dmax = cdmaxb            
    }
    ndays = ndays + 1
    if(MM %in% 1:12){
        if(ndays == DD){
            df_aux[nrow(df_aux)+1,] <- df_s[i,]
            
        } else {
            df_aux[nrow(df_aux)+1,]<-c(YY,MM,ndays,0,0,0,0)
            print(df_aux[nrow(df_aux)+1,])
        }
        if(ndays == dmax[MM]){
            #print(paste(YY,ndays))
            ndays = 0
        } 
    }        
}

In [11]:
df_sndata<-read.csv2("~/min03nasa_2023/to3soft_13ABR2018_org/snData/sndata.dat", sep = '\t',header = F)
df_sndataskim<-read.csv2("~/min03nasa_2023/to3soft_13ABR2018_org/snData/sndataskim.dat", sep = '\t',header = F)

In [12]:
df_UD<-read.csv2("~/min03nasa_2023/to3soft_13ABR2018_org/skim_LET/LET.dat", sep = '\t',header = F)

In [13]:
df_UD <- type.convert(df_UD, as.is = TRUE)

In [14]:
min(df_UD$V4)

[1] -3

In [15]:
min(df_sndataskim$V5)

[1] 0

In [16]:
dim(df_sndataskim)

[1] 16071     8